### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by gino-hong** [gino-hong/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Set the background to the color green.
- [x] Add image of a car.
- [x] Make sure the car starts out facing east.
